### ISSUE TITLE
range calendar time picker UI bugs

### ISSUE THREAD

**Issue by VictorKid** [react-component/calendar#156]
go to range calendar demo page [range-calendar](http://react-component.github.io/calendar/examples/antd-range-calendar.html)
1. select a range of days,
2. select time,
3. the start of date won't sync with what we just selected.

**Comment by DaveSpivey** [comment]
I'm having this same issue - and as VictorKid said, the start date is wrong on the demo too. Seems RangeCalendar is passing the initial `props.value` to CalendarPart and down to CalendarHeader - when it should be passing `state.selectedValue[0]`. `props.value` doesn't change as you click around and select different date ranges so it just gets stuck on the initial value and like VictorKid said, gets out of sync.

A quick fix could be to add this conditional to RangeCalendar.js - at the end of `getStartValue()` instead of just returning props.value:

`if (this.state.showTimePicker && selectedValue[0]) {
      return selectedValue[0];
    }
    return value;`

**Comment by VictorKid** [comment]
@DaveSpivey thx, I will try later.
