### ISSUE TITLE
第一个事例照搬 select time TimePanel 只有时和秒,请问为什么呢

### ISSUE THREAD

**Issue by Grifree** [react-component/calendar#185]
![image](https://cloud.githubusercontent.com/assets/14190298/20739273/26c673ac-b6f4-11e6-8a65-021cf5326006.png)
版本@7.5.1
@hui

**Comment by Grifree** [comment]
版本@7.5.1

**Comment by Grifree** [comment]
@luolonghao

**Comment by xiaoDC** [comment]
https://github.com/react-component/calendar/blob/master/src/Calendar.jsx#L205 这行后面应该加       showMinute: true  这样就可以了 @luolonghao

**Comment by nimojs** [comment]
解决方法确实是 @xiaoDC 所发的

目前暂时用 `const timePickerElement = <TimePickerPanel showMinute={true} />` 解决

郁闷的是示例代码中并没有 `showMinute`

**Comment by zhuhehe1990** [comment]
I came across with the same problem today. We used old version of rc-calendar and rc-time-picker and just update it today.

Its strange that in 6.0.2 there is no showMinute set neither but we had full UI with hour, minute and second.

Is there any other way to fix this problem(like a API) without changing these source code? we are using the online npm source code instead of localizing it.
