### ISSUE TITLE
Calendar Picker always shows selected day for each month

### ISSUE THREAD

**Issue by codecvlt** [react-component/calendar#283]
E.g, if pickers value is 12/06/2017, and you skip forward and back a month, the 6th is always highlighted.

I would only expect the 6th of December to be highlighted.

**Comment by benjycui** [comment]
This style is for keyboard accessibility.

![image](https://user-images.githubusercontent.com/3580607/28650091-d93eed34-72ab-11e7-87e6-09e723f1f1c7.png)

**Comment by juliankmazo** [comment]
Hi!
What do you mean by "keyboard accessibility"
I'm having the same issue but I don't understand why this behavior (it shows the selected number of the day highlight for every month instead of just highlighting the actual selected date)

And how can I disable that behavior? It looks like a bug. 
Thanks btw for the great work. Awesome component 😄 
<img width="381" alt="screen shot 2018-01-11 at 5 28 52 pm" src="https://user-images.githubusercontent.com/7906134/34850698-fac61c84-f6f4-11e7-8469-836cb79798cf.png">
<img width="380" alt="screen shot 2018-01-11 at 5 28 59 pm" src="https://user-images.githubusercontent.com/7906134/34850699-fae2be70-f6f4-11e7-979b-699299a6e78c.png">
<img width="380" alt="screen shot 2018-01-11 at 5 29 05 pm" src="https://user-images.githubusercontent.com/7906134/34850700-fafd1324-f6f4-11e7-94b3-678ac0e58a48.png">
<img width="377" alt="screen shot 2018-01-11 at 5 29 13 pm" src="https://user-images.githubusercontent.com/7906134/34850701-fb156f6e-f6f4-11e7-98d8-1b6da2f30dd6.png">

**Comment by VectorM** [comment]
up
